from statistics import multimode
def freq(text, k):
    words = []
    for i in range(len(text) - k + 1):
        word = text[i: i + k]
        words.append(word)
    return multimode(words)
    
list = freq("CCGTTATGAATACATCGCCCTTATGACCTTATGAGGGCTGTTAGGGGCTGTTAGCACCAGCTGCCTTATGACCGTTATGAACCTTATGAGGGCTGTTAGTACATCGCCACCAGCTGGGGCTGTTAGTACATCGCCCGTTATGAACCGTTATGAACCGTTATGAACACCAGCTGTACATCGCCCGTTATGAACACCAGCTGCCTTATGAGGGCTGTTAGCACCAGCTGCCGTTATGAATACATCGCCCTTATGATACATCGCCCGTTATGAAGGGCTGTTAGTACATCGCCCTTATGACCTTATGAGGGCTGTTAGCCTTATGACCTTATGACACCAGCTGCACCAGCTGCACCAGCTGCCTTATGAGGGCTGTTAGCCTTATGATACATCGCTACATCGCCCTTATGACACCAGCTGCCTTATGACCTTATGATACATCGCCCGTTATGAATACATCGCCCGTTATGAACCTTATGACACCAGCTGCCGTTATGAACACCAGCTGCCTTATGAGGGCTGTTAGCCTTATGACCTTATGAGGGCTGTTAGGGGCTGTTAGTACATCGCCCTTATGATACATCGCCCTTATGACCTTATGACCTTATGACACCAGCTGCCGTTATGAACACCAGCTGGGGCTGTTAGTACATCGCCCTTATGATACATCGCCCTTATGACCTTATGACCTTATGACACCAGCTGGGGCTGTTAGCCTTATGACCGTTATGAACCTTATGACCTTATGACCGTTATGAACCTTATGACCTTATGATACATCGCGGGCTGTTAGTACATCGCCCGTTATGAACACCAGCTGGGGCTGTTAGCACCAGCTGCCTTATGACCTTATGACCGTTATGAACCGTTATGAATACATCGCGGGCTGTTAGGGGCTGTTAG", 14)
for i in list:
    print (i, end=' ')